name: elderly_care_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
    
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  js: ^0.7.0
  
  # State management
  provider: ^6.1.1
  
  # UI packages
  flutter_local_notifications: ^15.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  shimmer: ^3.0.0
  
  # Location services
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  
  # Sensors for fall detection
  sensors_plus: ^4.0.2
  
  # Utility packages
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  table_calendar: ^3.1.3
  google_fonts: ^6.2.1
  location: ^6.0.2
  onesignal_flutter: ^5.2.2
  flutter_launcher_icons: ^0.14.3
  flutter_map: ^6.1.0  # Free OpenStreetMap implementation
  latlong2: ^0.9.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  assets:
    - assets\app_icon.png
    - assets\images\register_image.jpg
  uses-material-design: true